/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DBCreatorFrame.java
 *
 * Created on 2011-5-14, 17:34:35
 */
package edoor.Data.UI;

/**
 *
 * @author Geng Xuehong
 */
public class DBCreatorFrame extends javax.swing.JFrame {

    /** Creates new form DBCreatorFrame */
    public DBCreatorFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edoor/Data/UI/Bundle"); // NOI18N
        setTitle(bundle.getString("DBCreatorFrame.title")); // NOI18N

        menuFile.setText(bundle.getString("DBCreatorFrame.menuFile.text")); // NOI18N

        jMenuItem1.setText(bundle.getString("DBCreatorFrame.jMenuItem1.text")); // NOI18N
        menuFile.add(jMenuItem1);

        menuMain.add(menuFile);

        menuEdit.setText(bundle.getString("DBCreatorFrame.menuEdit.text")); // NOI18N
        menuMain.add(menuEdit);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DBCreatorFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuBar menuMain;
    // End of variables declaration//GEN-END:variables
}
